### PR TITLE
build: Fix undefined references.

### PR DESCRIPTION
**Pull request by orbea**
When building lpe with slibtool (https://dev.midipix.org/cross/slibtool) it fails.
```
rdlibtool --tag=CC --mode=link clang -I../../src -g -O2 -no-undefined -avoid-version -module -export-dynamic -rpath /usr/local/lib/lpe -o cmode.la cmode.lo

rdlibtool: lconf: {.name="libtool"}.
rdlibtool: fdcwd: {.fdcwd=AT_FDCWD, .realpath="/tmp/lpe/src/modes"}.
rdlibtool: lconf: fstatat(AT_FDCWD,".",...) = 0 {.st_dev = 34, .st_ino = 163379}.
rdlibtool: lconf: openat(AT_FDCWD,"libtool",O_RDONLY,0) = -1 [ENOENT].
rdlibtool: lconf: openat(AT_FDCWD,"../",O_DIRECTORY,0) = 3.
rdlibtool: lconf: fstat(3,...) = 0 {.st_dev = 34, .st_ino = 163341}.
rdlibtool: lconf: openat(3,"libtool",O_RDONLY,0) = -1 [ENOENT].
rdlibtool: lconf: openat(3,"../",O_DIRECTORY,0) = 4.
rdlibtool: lconf: fstat(4,...) = 0 {.st_dev = 34, .st_ino = 163182}.
rdlibtool: lconf: openat(4,"libtool",O_RDONLY,0) = 3.
rdlibtool: lconf: found "/tmp/lpe/libtool".
rdlibtool: link: ln -s /dev/null .libs/cmode.a.disabled
rdlibtool: link: clang .libs/cmode.o -I../../src -g -O2 -shared -fPIC -Wl,--no-undefined -o .libs/cmode.so -Wl,--export-dynamic
/usr/bin/ld: .libs/cmode.o: in function `mode_accept':
/tmp/lpe/src/modes/cmode.c:23: undefined reference to `mode_util_accept_extensions'
/usr/bin/ld: /tmp/lpe/src/modes/cmode.c:24: undefined reference to `mode_util_accept_on_request'
/usr/bin/ld: .libs/cmode.o: in function `mode_init':
/tmp/lpe/src/modes/cmode.c:31: undefined reference to `cfg_get_option_int_with_default'
/usr/bin/ld: /tmp/lpe/src/modes/cmode.c:32: undefined reference to `cfg_get_option_int_with_default'
/usr/bin/ld: /tmp/lpe/src/modes/cmode.c:33: undefined reference to `cfg_get_option_int_with_default'
/usr/bin/ld: /tmp/lpe/src/modes/cmode.c:34: undefined reference to `cfg_get_option_int_with_default'
/usr/bin/ld: /tmp/lpe/src/modes/cmode.c:35: undefined reference to `cfg_get_option_int_with_default'
/usr/bin/ld: .libs/cmode.o: in function `mode_enter':
/tmp/lpe/src/modes/cmode.c:47: undefined reference to `mode_util_set_slang_color'
/usr/bin/ld: /tmp/lpe/src/modes/cmode.c:48: undefined reference to `mode_util_set_slang_color'
/usr/bin/ld: /tmp/lpe/src/modes/cmode.c:49: undefined reference to `mode_util_set_slang_color'
/usr/bin/ld: /tmp/lpe/src/modes/cmode.c:50: undefined reference to `mode_util_set_slang_color'
/usr/bin/ld: /tmp/lpe/src/modes/cmode.c:51: undefined reference to `mode_util_set_slang_color'
/usr/bin/ld: .libs/cmode.o:/tmp/lpe/src/modes/cmode.c:52: more undefined references to `mode_util_set_slang_color' follow
/usr/bin/ld: .libs/cmode.o: in function `mode_flashbrace':
/tmp/lpe/src/modes/cmode.c:175: undefined reference to `set_scr_col'
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
rdlibtool: exec error upon slbt_exec_link_create_library(), line 1446: (see child process error messages).
rdlibtool: < returned to > slbt_exec_link(), line 1868.
make[2]: *** [Makefile:538: cmode.la] Error 2
make[2]: Leaving directory '/tmp/lpe/src/modes'
make[1]: *** [Makefile:598: install-recursive] Error 1
make[1]: Leaving directory '/tmp/lpe/src'
make: *** [Makefile:524: install-recursive] Error 1
```
This is because the libraries in the `modes/` directory use `-no-undefined`, but the required references are only compiled into the `lpe` binary with no way to link the modes libraries. GNU libtool does not complain because it silently ignores `-no-undefined`...

I fixed this by moving the required code to the `src/lib/` directory where it is compiled into a helper library that is never installed and can be used to link everything accordingly.

The alternative would be to drop `-no-undefined`.

### CODE REVIEW

**Comment by orbea** [comment]
Also see this gentoo issue: https://bugs.gentoo.org/778581

**Comment by AdamMajer** [comment]
But these are not meant to be libraries. They are plugins. The symbols are resolved in the main executable.

**Comment by orbea** [comment]
From this line they are being compiled as libraries.

https://github.com/AdamMajer/lpe/blob/master/src/modes/Makefile.am#L9

If the symbols will not be resolved at build time then maybe its best to just remove `-no-undefined`? With GNU libtool there would be no difference since it just ignores the flag.

**Comment by AdamMajer** [comment]
Correct. The -no-undefined flag doesn't really make sense here. But these are legacy sources that haven't changed in  close to a generation now :-) Thanks!

**Pull request closed without merging**
